### ISSUE TITLE
use as a library

### ISSUE THREAD

**Issue by EugenMayer** [sjeandeaux/nexus-cli#10]
Thank you for your work on this!

Are you encouraging using this as a library to implement artifact transports to sonatype nexus? i am in need of some automation and also right now have written an concourse-ci resource to upload to nexus using curl ( in go ) .. but could think about using your library too.

Are there any plans to implement artifact deletion?

**Comment by sjeandeaux** [comment]
Hi, 

Thanks to use this library.
We plan to implement the deletion at the end of january 2018.

**Comment by sjeandeaux** [comment]
It is done in 0.5.0. @EugenMayer

**Comment by EugenMayer** [comment]
@sjeandeaux thank you a lot!
